version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ts-layers"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "ts-layers"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
